### ISSUE TITLE
This only works for flask-wtf < 0.9.0

### ISSUE THREAD

**Issue by pjvandehaar** [lpolepeddi/intro-to-flask#3]
Could you add a notice about that?  Perhaps also to the nettuts page?

**Comment by florije1988** [comment]
@pjvandehaar it is to old code, you can change the code for your self.
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SubmitField, validators, ValidationError, TextField, PasswordField

**Comment by pjvandehaar** [comment]
Alright, thanks.
